apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: dunkin-voice
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjYWR1bmtpbmFjci5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiY2FkdW5raW5hY3IiLCJwYXNzd29yZCI6IjdsdUllTEpJaFZObmFIQWZnclRrenJ0Zm5WSXZWRTdUTlVGbFhrbmQ4cFNXaDJQZEU4ZlFKUVFKOTlDQ0FDSFlIdjZFcWc3TkFBQUNBWkNSTUJ5cCIsImF1dGgiOiJZMkZrZFc1cmFXNWhZM0k2TjJ4MVNXVk1Ta2xvVms1dVlVaEJabWR5Vkd0NmNuUm1ibFpKZGxaRk4xUk9WVVpzV0d0dVpEaHdVMWRvTWxCa1JUaG1VVXBSVVVvNU9VTkRRVU5JV1VoMk5rVnhaemRPUVVGQlEwRmFRMUpOUW5sdyJ9fX0=