apiVersion: v1
kind: Service
metadata:
  name: dunkin-voice-service
  namespace: dunkin-voice
spec:
  type: NodePort
  selector:
    app: dunkin-voice-assistant
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
